apiVersion: apps/v1
kind: Deployment
metadata:
  name: foo
  labels:
    app: foo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: foo
  template:
    metadata:
      labels:
        app: foo
    spec:
      containers:
      - name: foo
        image: bhargavshah86/kube-test:v0.1
        ports:
        - containerPort: 80
        ##args:
        - #"-text=Hello World! This is a Baeldung Kubernetes with kind App"
